# configuration for "master" branch
# build in Release mode 
-
  branches:
    only:
      - master
  version: 2.0.{build}
  configuration: Release
  platform: Any CPU
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  build:
    publish_nuget: true
    verbosity: minimal
  build_script:
    - msbuild GoogleMapsServices.sln /p:Configuration=Release
    - msbuild GoogleMapsServices.sln /p:Configuration=Release-Net35
    - msbuild GoogleMapsServices.sln /p:Configuration=Release-Net40
    - nuget pack src/Client/Client.nuspec -Version %APPVEYOR_BUILD_VERSION%
  test: off
  artifacts: 
    - path: '**\*.nupkg'
  deploy:
    - provider: NuGet
      api_key:
        secure: pi98jdOOgUknVbO9zAh2LJiCCsc48HRZ3sGMvCX7DbkeBglS/T1gPcpGee9oOvqO
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true       # deploy on tag push only
    - provider: NuGet
      server: https://ci.appveyor.com/nuget/velyo
      api_key:
        secure: qrQMiOtUhrEB5U/xeSttpzWypIKBU72NM9L5+wyRnS4=
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true       # deploy on tag push only

# configuration for "net35" branch
# build in Release-Net35 mode 
-
  branches:
    only:
      - net35
  version: 2.0.{build}
  configuration: Release-Net35
  platform: Any CPU
  build:
    verbosity: minimal
  test: off

# configuration for "net40" branch
# build in Release-Net40 mode 
-
  branches:
    only:
      - net40
  version: 2.0.{build}
  configuration: Release-Net40
  platform: Any CPU
  build:
    verbosity: minimal
  test: off